version: 2
project_name: gotfhub
report_sizes: false
metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

env:
  - DOCKER_CONFIG=$HOME/.docker/planesailingio
builds:
  - id: default
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    no_unique_dist_dir: true
    dir: .
    main: .
    binary: "bin/{{ .Version }}/{{ .Os }}/{{ .Arch }}/gotfhub"

    builder: go
    gobinary: go
    command: build
    env:
      - CGO_ENABLED=0


dockers:
- image_templates:
  - planesailingio/gotfhub:latest-amd64
  - planesailingio/gotfhub:{{ .Version }}-amd64
  - planesailingio/gotfhub:{{ .Major }}-amd64
  - planesailingio/gotfhub:{{ .Major }}.{{ .Minor }}-amd64
  use: buildx
  skip_push: false
  # templated_dockerfile: Dockerfile
  build_flag_templates:
    - "--pull"
    # - "--label=io.planesailing.cli.created={{.Date}}"
    # - "--label=io.pigeono.cli.title={{.ProjectName}}"
    # - "--label=io.pigeono.cli.revision={{.FullCommit}}"
    # - "--label=io.pigeono.cli.version={{.Version}}"
    - "--build-arg=VERSION={{ .Version }}"
    - "--build-arg=OS=linux"
    - "--build-arg=ARCH=amd64"
    - "--platform=linux/amd64"
# - image_templates:
#   - planesailingio/gotfhub:latest-arm64
#   - planesailingio/gotfhub:{{ .Version }}-arm64
#   - planesailingio/gotfhub:{{ .Major }}-arm64
#   - planesailingio/gotfhub:{{ .Major }}.{{ .Minor }}-arm64
#   use: buildx
#   # templated_dockerfile: Dockerfile
#   build_flag_templates:
#     - "--pull"
#     - "--label=io.pigeono.cli.created={{.Date}}"
#     - "--label=io.pigeono.cli.title={{.ProjectName}}"
#     - "--label=io.pigeono.cli.revision={{.FullCommit}}"
#     - "--label=io.pigeono.cli.version={{.Version}}"
#     - "--build-arg=VERSION={{ .Version }}"
#     - "--build-arg=OS=linux"
#     - "--build-arg=ARCH=arm64"
#     - "--platform=linux/arm64"
#   goarch: arm64

docker_manifests:
- name_template: "planesailingio/gotfhub:latest"
  skip_push: false
  image_templates:
    - "planesailingio/gotfhub:latest-amd64"
    # - "planesailingio/gotfhub:latest-arm64"
- name_template: "planesailingio/gotfhub:{{ .Version }}"
  image_templates:
    - "planesailingio/gotfhub:{{ .Version }}-amd64"
    # - "planesailingio/gotfhub:{{ .Version }}-arm64"
- name_template: "planesailingio/gotfhub:{{ .Major }}"
  image_templates:
    - "planesailingio/gotfhub:{{ .Major }}-amd64"
    # - "planesailingio/gotfhub:{{ .Major }}-arm64"
- name_template: "planesailingio/gotfhub:{{ .Major }}.{{ .Minor }}"
  image_templates:
    - "planesailingio/gotfhub:{{ .Major }}.{{ .Minor }}-amd64"
    # - "planesailingio/gotfhub:{{ .Major }}.{{ .Minor }}-arm64"
brews:
  - name: gotfhub
    repository:
      owner: planesailingio
      name: homebrew-tools
      branch: main
      git:
        private_key: /Users/server/.ssh/id_rsa

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
  algorithm: sha256

gomod:
  gobinary: go

changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^updaated'

release:
  github:
    owner: planesailingio
    name: gotfhub
  name_template: "{{.ProjectName}} v{{.Version}}"

  draft: false
  mode: replace
  header: |
    # 🚀 A new goTFHub release
    Thanks for checking this version out, find out more below.

  footer: |
    ## Thanks for supporting,

    Those were the changes on {{ .Tag }}!
    Don't forget if you like the tool, don't forget to star it ⭐!
  skip_upload: false
  disable: false
